## Chapter 4 – Exercise 4:  Sử dụng Mysql Connector để thực hiện các truy vấn có tham số

#### Học viên thực hiện các yêu cầu sau và đối chiếu với kết quả cho trước (nếu có):

In [1]:
from mysql.connector import connect

In [2]:
conn = connect(host='localhost', port=3308, database='salesdb', user='root', password='')

In [3]:
# Câu 1: Liệt kê danh sách các sản phẩm do công ty 'Tokyo Traders' cung cấp, với tham số tên công ty do người dùng nhập vào
sql = """
SELECT p.*, s.CompanyName
FROM products p JOIN suppliers s ON p.SupplierId=s.Id
WHERE s.CompanyName=%s
"""

In [4]:
cur = conn.cursor()
#name = 'Tokyo Traders'
name = input("Nhập tên nhà cung cấp: ")
data = (name,)
cur.execute(sql, data)
row = cur.fetchone()
while row:
    print(row)
    row = cur.fetchone() 
cur.close()   
conn.close()

Nhập tên nhà cung cấp: Tokyo Traders
(9, 'Mishi Kobe Niku', 4, Decimal('97.00'), '18 - 500 g pkgs.', 1, 'Tokyo Traders')
(10, 'Ikura', 4, Decimal('31.00'), '12 - 200 ml jars', 0, 'Tokyo Traders')
(74, 'Longlife Tofu', 4, Decimal('10.00'), '5 kg pkg.', 0, 'Tokyo Traders')


<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>Nhập tên nhà cung cấp: Tokyo Traders
(9, 'Mishi Kobe Niku', 4, Decimal('97.00'), '18 - 500 g pkgs.', 1, 'Tokyo Traders')
(10, 'Ikura', 4, Decimal('31.00'), '12 - 200 ml jars', 0, 'Tokyo Traders')
(74, 'Longlife Tofu', 4, Decimal('10.00'), '5 kg pkg.', 0, 'Tokyo Traders')
</pre>
  
</details>

In [5]:
def run_sql(sql, data):
    cur = conn.cursor()
    cur.execute(sql, data)
    row = cur.fetchone()
    while row:
        print(row)
        row = cur.fetchone()    
    cur.close()

In [6]:
conn = connect(host='localhost', port=3308, database='salesdb', user='root', password='')

In [7]:
# Câu 2: Cập nhật đơn giá tăng thêm 3usd cho các sản phẩm do công ty 'Tokyo Traders' cung cấp, 
# với tham số đơn giá tăng và tên công ty do người dùng nhập vào
sql = """
UPDATE products p JOIN suppliers s ON p.SupplierId=s.Id
SET UnitPrice=UnitPrice+%s
WHERE s.CompanyName=%s
"""

In [8]:
#name = 'Tokyo Traders'
#price = 3
price = input("Nhập giá trị đơn giá tăng thêm: ")
name = input("Nhập tên nhà cung cấp: ")
data = (price, name)
run_sql(sql, data)

Nhập giá trị đơn giá tăng thêm: 3
Nhập tên nhà cung cấp: Tokyo Traders


<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>Nhập giá trị đơn giá tăng thêm: 3
Nhập tên nhà cung cấp: Tokyo Traders
</pre>
  
</details>

In [9]:
# Câu 3: Thêm sản phẩm mới vào bảng Products với các giá trị tương ứng do người dùng nhập vào. 
# Sau khi thêm, xuất thông báo hỏi người dùng có thêm tiếp hay không (Y/N). 
# Nếu trả lời Y sẽ cho phép thêm tiếp sản phẩm mới, nếu trả lời N sẽ thoát quá trình thêm sản phẩm.



In [10]:
# Câu 4: Xóa thông tin đơn đặt hàng theo số đặt hàng (OrderId), trong đó số đặt hàng do người dùng nhập vào



In [11]:
conn.close()