ALTER TABLE CATEGORIES
ADD CONSTRAINT UC_Categories UNIQUE(Categoryname);

ALTER TABLE PRODUCTS
ADD CONSTRAINT FK_Products_Categories 
FOREIGN KEY(Categoryid) REFERENCES CATEGORIES(Categoryid);

ALTER TABLE PRODUCTS
ADD CONSTRAINT CHK_Products_unitprice CHECK(Unitprice >= 0);

ALTER TABLE ORDERDETAILS
ALTER qty SET DEFAULT 1;