## Chapter 4 – Exercise 4:  Sử dụng Mysql Connector để thực hiện các truy vấn có tham số

#### Học viên thực hiện các yêu cầu sau và đối chiếu với kết quả cho trước (nếu có):

In [1]:
# from mysql.connector import connect
import pandas as pd
import numpy as np
%load_ext sql

In [2]:
# conn = connect(host='localhost', port=3308, database='salesdb', user='root', password='')
user = 'root'
password = 'root'
host = 'localhost:8889'
database = 'salesdb'
connection_string = "mysql+pymysql://{user}:{password}@{host}/{database}?charset=UTF8".format(user=user, password=password, host=host, database=database)
try:
    p = %sql $connection_string
    print('Database connected!')
except Exception:
    print('Unabale to connect.')

Database connected!


In [5]:
# Câu 1: Liệt kê danh sách các sản phẩm do công ty 'Tokyo Traders' cung cấp, với tham số tên công ty do người dùng nhập vào

In [4]:
def products_by_supplier_name():
    company_name = input('Please input supplier name: ')
    sql_script = """
    select p.*
    from products p
    join suppliers s on p.supplierid = s.id
    where companyname = '{}'
    """.format(company_name)
    df = %sql $sql_script
    if df.DataFrame().empty:
        return print('Can not find supplier name')
    return df.DataFrame()
products_by_supplier_name()

 * mysql+pymysql://root:***@localhost:8889/salesdb?charset=UTF8
3 rows affected.


Id      ProductName  SupplierId UnitPrice           Package IsDiscontinued
0   9  Mishi Kobe Niku           4     97.00  18 - 500 g pkgs.        b'\x01'
1  10            Ikura           4     31.00  12 - 200 ml jars        b'\x00'
2  74    Longlife Tofu           4     10.00         5 kg pkg.        b'\x00'

<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>Nhập tên nhà cung cấp: Tokyo Traders
(9, 'Mishi Kobe Niku', 4, Decimal('97.00'), '18 - 500 g pkgs.', 1, 'Tokyo Traders')
(10, 'Ikura', 4, Decimal('31.00'), '12 - 200 ml jars', 0, 'Tokyo Traders')
(74, 'Longlife Tofu', 4, Decimal('10.00'), '5 kg pkg.', 0, 'Tokyo Traders')
</pre>
  
</details>

In [6]:
# Câu 2: Cập nhật đơn giá tăng thêm 3usd cho các sản phẩm do công ty 'Tokyo Traders' cung cấp, 
# với tham số đơn giá tăng và tên công ty do người dùng nhập vào

In [9]:
def update_products_by_supplier_name():
    increase_amount = input('Please input increase amount: ')
    company_name = input('Please input supplier name: ')
    sql_script = """
    update products p
    join suppliers s on p.supplierid = s.id
    set p.unitprice = p.unitprice + {}
    where companyname = '{}'
    """.format(increase_amount, company_name)
    %sql $sql_script
    print('Updated products: ')
    sql_show = """
    select p.*
    from products p
    join suppliers s on p.supplierid = s.id
    where companyname = '{}'
    """.format(company_name)
    df = %sql $sql_show
    if df.DataFrame().empty:
        return print('Can not find supplier name to update')
    return df.DataFrame()
update_products_by_supplier_name()

 * mysql+pymysql://root:***@localhost:8889/salesdb?charset=UTF8
3 rows affected.
Updated products: 
 * mysql+pymysql://root:***@localhost:8889/salesdb?charset=UTF8
3 rows affected.


Id      ProductName  SupplierId UnitPrice           Package IsDiscontinued
0   9  Mishi Kobe Niku           4    103.00  18 - 500 g pkgs.        b'\x01'
1  10            Ikura           4     37.00  12 - 200 ml jars        b'\x00'
2  74    Longlife Tofu           4     16.00         5 kg pkg.        b'\x00'

<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>Nhập giá trị đơn giá tăng thêm: 3
Nhập tên nhà cung cấp: Tokyo Traders
</pre>
  
</details>

In [23]:
# Câu 3: Thêm sản phẩm mới vào bảng Products với các giá trị tương ứng do người dùng nhập vào. 
# Sau khi thêm, xuất thông báo hỏi người dùng có thêm tiếp hay không (Y/N). 
# Nếu trả lời Y sẽ cho phép thêm tiếp sản phẩm mới, nếu trả lời N sẽ thoát quá trình thêm sản phẩm.
def insert_new_products():
    continue_insert = 1
    while continue_insert == 1:
        product_name = input('Product name: ')
        supplier_id = input('Supplier ID: ')
        unit_price = input('Unit price: ')
        package = input('Package: ')
        isdiscontinued = input('Is Discontinued? (1 or 0): ')
        %sql alter table products modify id int(10) auto_increment not null;
        sql_script = """
        insert into products (productname, supplierid, unitprice, package, isdiscontinued)
        values ('{}', {}, {}, '{}', {})
        """.format(product_name, supplier_id, unit_price, package, isdiscontinued)
        %sql $sql_script
        print('Updated products: ')
        sql_show = """
        select p.*
        from products p
        where supplierid = '{}'
        """.format(supplier_id)
        df = %sql $sql_show
        print(df.DataFrame())
        continue_insert = int(input('Do you want to continue insert data? (1 or 0): '))
insert_new_products()

 * mysql+pymysql://root:***@localhost:8889/salesdb?charset=UTF8
0 rows affected.
 * mysql+pymysql://root:***@localhost:8889/salesdb?charset=UTF8
1 rows affected.
Updated products: 
 * mysql+pymysql://root:***@localhost:8889/salesdb?charset=UTF8
6 rows affected.
   id      ProductName  SupplierId UnitPrice           Package IsDiscontinued
0   9  Mishi Kobe Niku           4    103.00  18 - 500 g pkgs.        b'\x01'
1  10            Ikura           4     37.00  12 - 200 ml jars        b'\x00'
2  74    Longlife Tofu           4     16.00         5 kg pkg.        b'\x00'
3  79              New           4     30.00             20 kg        b'\x00'
4  80          Pak Nam           4     20.00              2 kg        b'\x00'
5  81             Cafe           4     12.00            0.5 kg        b'\x00'
 * mysql+pymysql://root:***@localhost:8889/salesdb?charset=UTF8
0 rows affected.
 * mysql+pymysql://root:***@localhost:8889/salesdb?charset=UTF8
1 rows affected.
Updated products: 
 * mysql+py

In [24]:
# Câu 4: Xóa thông tin đơn đặt hàng theo số đặt hàng (OrderId), trong đó số đặt hàng do người dùng nhập vào

In [25]:
def delete_order():
    order_id = int(input('Input order ID to delete: '))
    %sql delete from orders where id = :order_id
delete_order()

 * mysql+pymysql://root:***@localhost:8889/salesdb?charset=UTF8
1 rows affected.


In [7]:
conn.close()